[[navbar]]
    identifier = "minecraft"
    name = "Minecraft"
    url = "/minecraft/"
    weight = 1
    [[navbar]]
        parent = 'minecraft'
        identifier = "versions"
        name = "Versións"
        url = "/minecraft/versions/"
        weight = 1
        [[navbar]]
            parent = 'versions'
            identifier = "java"
            name = "Java"
            url = "/minecraft/versions/java/"
            weight = 1
            [[navbar]]
                parent = 'java'
                identifier = "cronoloxia"
                name = "Cronoloxía"
                url = "/minecraft/versions/java/cronoloxia"
                weight = 1
            [[navbar]]
                parent = 'java'
                identifier = "informacion"
                name = "Información"
                url = "/minecraft/versions/java/informacion"
                weight = 2
        [[navbar]]
            parent = 'versions'
            identifier = "bedrock"
            name = "Bedrock"
            url = "/minecraft/versions/bedrock/"
            weight = 2

[[navbar]]
    identifier = "granxas"
    name = "Granxas"
    url = "/granxas/"
    weight = 2
    [[navbar]]
        parent = "granxas"
        identifier = "ferro"
        name = "Ferro"
        url = "/granxas/ferro/"
        weight = 1
    [[navbar]]
        parent = "granxas"
        identifier = "lama"
        name = "Lama"
        url = "/granxas/lama/"
        weight = 10

[[navbar]]
    identifier = "ferramentas"
    name = "Ferramentas"
    url = "/ferramentas/"
    weight = 3

[[navbar]]
    identifier = "redstone"
    name = "Redstone"
    url = "/redstone/"
    weight = 4

[[navbar]]
    identifier = "mods"
    name = "Mods"
    url = "/mods/"
    weight = 5

[[navbar]]
    identifier = "creadores"
    name = "Creadores"
    url = "/creadores/"
    weight = 6

[[navbar]]
    identifier = "servidores"
    name = "Servidores"
    url = "/servidores/"
    weight = 7

[[navbar]]
    identifier = "sobre"
    name = "Sobre"
    url = "/sobre/"
    weight = 8
